create table if not exists public.non_native_students (
  id bigint generated by default as identity primary key,
  student_name text not null,
  gender text not null check (gender in ('بنين','بنات')),
  stage text not null,
  grade text not null,
  section_name text not null,
  curriculum text not null check (curriculum in ('أمريكي','بريطاني')),
  submitted_by text not null,
  created_at timestamptz not null default now()
);
alter table public.non_native_students enable row level security;
drop policy if exists "public can submit non native students" on public.non_native_students;
create policy "public can submit non native students" on public.non_native_students for insert to anon, authenticated with check (true);
drop policy if exists "admins can read non native students" on public.non_native_students;
create policy "admins can read non native students" on public.non_native_students for select to authenticated using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));
create index if not exists non_native_students_sort_idx on public.non_native_students(gender,stage,curriculum,grade,section_name);
